### ISSUE TITLE
How to fix the cursor style?

### ISSUE THREAD

**Issue by JamesKid** [itchyny/vim-cursorword#12]
How to fix the cursor style? I don't like the underline style, i love backgroundcolor style.

**Comment by itchyny** [comment]
Configure `CursorWord[01]` highlight colors. The difference of 0 and 1 is that CursorWord1 is used for the word in the current line if you enable the cursorline option.
```vim
let g:cursorword_highlight = 0
autocmd Colorscheme * highlight CursorWord0 ctermbg=52 guibg=#5f0000
autocmd Colorscheme * highlight CursorWord1 ctermbg=52 guibg=#5f0000
```
