### ISSUE TITLE
Error happened when opening cmdwin with Neovim inccommand=nosplit

### ISSUE THREAD

**Issue by ghost** [itchyny/vim-cursorword#19]
`set inccommand=nosplit`と一緒に使い，cmdwinを開くとエラーが出ます

以下のvimrcと一緒に当該リポジトリ内で `nvim -u vimrc` をして確認しています

`nvim -v | head -1` は `NVIM v0.5.0-330-g71ee46acc`

```
let &rtp ..= ',' .. expand('<sfile>:h')

set icm=nosplit
```

---

```
iabc<ESC>
:s/ab<C-f>
```

```
Error detected while processing function cursorword#matchadd:
line   16:
E171: Missing :endif
E171: Missing :endif
```

(これは `:mes` をすることでエラーが確認できたんですが，普段の自分のvimrcではエラーが出て中断されてしまいます)

---

```
<C-c>
```

```
Error detected while processing function cursorword#timer_callback[1]..cursorword#matchadd:
line   16:
E171: Missing :endif
```

parenmatchでも似たようなエラーが出ます https://github.com/itchyny/vim-parenmatch/issues/5

**Comment by ghost** [comment]
ごめんなさい， NeoVim v0.4.3で試したら出なくなりました，neovimのバグな気がします
Closeします...

**Comment by itchyny** [comment]
I reported to https://github.com/neovim/neovim/issues/11818. This is a bug of neovim, not this plugin.

**Comment by ghost** [comment]
Great thanks!!!!!
