### ISSUE TITLE
Blinking On Movement

### ISSUE THREAD

**Issue by smhmd** [itchyny/vim-cursorword#20]
`cursorword` blinks when moving without changing the word.
Video:
[![video](https://user-images.githubusercontent.com/46059092/76647668-8838a900-655d-11ea-8445-59e925d22e7a.png)](https://i.imgur.com/ToQTHCa.mp4).

**Comment by itchyny** [comment]
This is an expected behavior after performance improvement (d00937def0674416ff315a43a49deb38cdbb11b6). If there're more requests, I'll add an option for the delay duration.

**Comment by weirane** [comment]
Same issue here. It would be appreciated if you add an option.

**Comment by itchyny** [comment]
I added `g:cursorword_delay` option. Configure `let g:cursorword_delay = 0` to update synchronously.
