### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by xzfc** [itchyny/vim-cursorword#23]
### Use case
I'm using `vim-cursorword` together with [`inkarkat/vim-mark`](https://github.com/inkarkat/vim-mark).
Underline of `vim-cursorword` takes precedence over marks placed by `vim-mark`.
This is inconvenient since there is no immediate visual feedback after marking a word by pressing `\m`. I have to move the cursor to see the marks.

* `vim-cursorword` has a priority of -1 (unconfigurable)
* `vim-mark` by default has a priority of -10 (configurable via `g:mwMaxMatchPriority`)
* both priorities have to be negative, otherwise, they would override `hlsearch`

### Feature request
I would like to configure `vim-cursorword` match priority.

Or leave it unconfigurable, but at least make it small enough, like `-100`. In this case it is possible to revert to the old behavior by setting `g:mwMaxMatchPriority` to e.g. `-200`.

Or, if it is possible, make both plugins not interfere with each other. I.e. make `vim-cursorword` underline not to override `vim-mark` backgrounds.

**Comment by itchyny** [comment]
I changed the priority to -100. Please confirm.

**Comment by xzfc** [comment]
Now it works as desired, thank you.
