### ISSUE TITLE
Unnecessary white background of cursorword appear when set cursorline

### ISSUE THREAD

**Issue by imuxin** [itchyny/vim-cursorword#24]
- Disable cursorline

.vimrc
```
" set cursorline
```

Result:
![disable_cursorline](https://user-images.githubusercontent.com/47353892/82426030-e8961a80-9ab9-11ea-8b5e-80527d3f7abb.png)

- Enable cursorline

.vimrc
```
set cursorline
highlight CursorLine cterm=none ctermfg=None
highlight Visual cterm=bold ctermbg=202 ctermfg=NONE
```

Result:
![enable_cursorline](https://user-images.githubusercontent.com/47353892/82426515-8984d580-9aba-11ea-877a-d15d2fdb00ca.png)

**I don't want the white background appear. How could I to hide or make it transparent?**

**Comment by itchyny** [comment]
What's the output of `:highlight CursorLine` and `:highlight CursorWord1`?

**Comment by imuxin** [comment]
I am not clear about the .vimrc status what "highlight xxx" commands are based on. I can show you my entire vimrc file content. You can test on your local environment.

```vimrc
scriptencoding utf-8
set encoding=utf-8
set nocompatible
set termguicolors
syntax enable
syntax on

set cursorline
highlight CursorLine cterm=none ctermfg=None
highlight Visual cterm=bold ctermbg=202 ctermfg=NONE


"+-----------------------+
"| VundleVim.vim configs |
"+-----------------------+

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'itchyny/vim-cursorword'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
```

**Comment by itchyny** [comment]
I can't still reproduce the issue. Please let me know the output of executing `:highlight CursorLine` and `:highlight CursorWord1` from the command line.

**Comment by itchyny** [comment]
Caused by termguicolors?

**Comment by imuxin** [comment]
`:highlight CursorLine`
![1](https://user-images.githubusercontent.com/47353892/82462852-adfaa500-9aee-11ea-8e05-91045ecd1f00.png)

---

`:highlight CursorWord1`
![2](https://user-images.githubusercontent.com/47353892/82462869-b18e2c00-9aee-11ea-8634-a801254c6864.png)

**Comment by imuxin** [comment]
Unset `termguicolors`

`:highlight CursorLine`
![3](https://user-images.githubusercontent.com/47353892/82463311-41cc7100-9aef-11ea-88d4-94e4ec89c9c3.png)

---

`:highlight CursorWord1`
![4](https://user-images.githubusercontent.com/47353892/82463357-50b32380-9aef-11ea-9d59-efd564340fe4.png)

**Comment by itchyny** [comment]
You don't set the guibg of CursorLine in your vimrc but it seems that it is set lazily somewhere. Adding `guibg=Grey40` to `highlight CursorLine` should fix this.

**Comment by imuxin** [comment]
It works! Thanks!
