### ISSUE TITLE
Configuring the delay

### ISSUE THREAD

**Issue by fnune** [itchyny/vim-cursorword#26]
Hey there, thanks for the plugin!

I'm wondering: can I configure the delay after which words get underlined? I have this effect where moving one character inside the word will refresh the underlining of that word, so it flashes a lot. With a longer delay/debounce, this could be a bit smoother.

**Comment by itchyny** [comment]
Please refer to `:h g:cursorword_delay`.

**Comment by fnune** [comment]
Thank you very much!

For anyone interested, I did this:

```
let g:cursorword_delay = 400
```
