### ISSUE TITLE
Can you make it highlight word under cursor not underline it ?

### ISSUE THREAD

**Issue by uunnxx** [itchyny/vim-cursorword#28]
Coc.vim has plugin coc-highlight, and coc-highlight can highlight the current word under the cursor but it's not as fast as your plugin.

If you can, please add an option where we can specify underline or highlight the word.

![highlight](https://user-images.githubusercontent.com/6236057/100550580-0378f100-328c-11eb-93de-26ff1e10d728.png)

**Comment by itchyny** [comment]
Please refer to #16.
