### ISSUE TITLE
Bug with latest neovim 

### ISSUE THREAD

**Issue by glepnir** [itchyny/vim-cursorword#29]
Hi  @itchyny  found something wrong with neovim head version

- version : `NVIM v0.5.0-dev+b0215afc8`
- env : mac os 10.15.7

## Problem
check this pic. the cursor in word `function`. but you can see it highlight the 1 with a space?
![image](https://user-images.githubusercontent.com/41671631/103255296-b6d82100-49c3-11eb-9c4b-99e2c9c3e068.png)

**Comment by itchyny** [comment]
Please describe your problem with the version of NeoVim, minimal init.vim to reproduce the issue and bisecting result if possible.
I tested with `NeoVim v0.5.0-dev+a06c256` with the following configuration but it works for me.
```vim
" using vim-plug
call plug#begin('~/.config/nvim/plugged')
Plug 'itchyny/vim-cursorword'
call plug#end()
```

**Comment by glepnir** [comment]
@itchyny  rewrite issue template. please check. Thanks .

**Comment by itchyny** [comment]
I cannot still reproduce.
<img width="212" alt="Screen Shot 2020-12-29 at 11 54 18" src="https://user-images.githubusercontent.com/375258/103255419-96609480-49cc-11eb-9af3-da1f3443db90.png">
```vim
function
let x = function()
let x = 1
```

**Comment by glepnir** [comment]
Aha . Thanks bug with my config sry.

**Comment by glepnir** [comment]
@itchyny  reopen. check this min.vim. It does not work. maybe caused by https://github.com/neovim/neovim/pull/13616
```vim
set rtp=path/to/itchyny/vim-cursorword

set foldenable
set foldmethod=indent
set shiftwidth=2
set autoindent
``

**Comment by itchyny** [comment]
Then this is a problem of NeoVim, not this plugin. Please report to the NeoVim issue tracker.
