### ISSUE TITLE
augroup cursorword has a bug

### ISSUE THREAD

**Issue by tenfyzhong** [itchyny/vim-cursorword#3]
augroup cursorword
  autocmd!
  autocmd VimEnter,ColorScheme \* call cursorword#highlight()
  autocmd VimEnter,WinEnter,BufEnter,CursorMoved,CursorMovedI \* call cursorword#matchadd()
augroup END

should be

augroup cursorword
  autocmd!
  autocmd VimEnter,WinEnter,BufEnter,ColorScheme \* call cursorword#highlight()
  autocmd VimEnter,WinEnter,BufEnter,CursorMoved,CursorMovedI \* call cursorword#matchadd()
augroup END

**Comment by itchyny** [comment]
No. Defining a highlight is enough on Vim's startup and when user changes the colorscheme.
