### ISSUE TITLE
No such highlight group name: CursorWord.

### ISSUE THREAD

**Issue by onlycalm** [itchyny/vim-cursorword#34]
![image](https://github.com/itchyny/vim-cursorword/assets/48640489/11736c74-7668-425c-b611-621c701d33e9)

When I use the latest master branch(SHA-371fdd7), moving the cursor will result in an error.
Fallback to tag: v0.8 will run normally.

**Comment by itchyny** [comment]
Please describe the issue with the complete configuration for reproduction and Vim version, OS version, etc. Simple vimrc is as follows;
```vim
set rtp+=~/.share/miv/cursorword/
filetype plugin on
```
and `vim -u ~/vimrc -N README.md` with Vim 9.0.1600 works well.

**Comment by itchyny** [comment]
Please describe the issue with the complete configuration for reproduction and Vim version, OS version, etc. Simple vimrc is as follows;
```vim
set rtp+=~/path/to/cursorword/
filetype plugin on
```
and `vim -u ~/vimrc -N README.md` with Vim 9.0.1600 works well.
