### ISSUE TITLE
Error detected while processing function cursorword#matchadd: No such highlight group name: CursorWord1

### ISSUE THREAD

**Issue by phongvcao** [itchyny/vim-cursorword#4]
I recently updated my `vim-cursorword` and received the following error message when starting vim:

```
Error detected while processing function cursorword#matchadd:
line 14:
No such highlight group name: CursorWord1
```

I hope the error would be fixed ASAP. For now I will have to disable the plugin altogether.

**Comment by itchyny** [comment]
Please paste the minimal vimrc to reproduce the error, otherwise I cannot investigate the reason.

**Comment by itchyny** [comment]
vimrc:

``` vim
set nocompatible
filetype off
set rtp+=/path/to/cursorword
filetype plugin on
syntax enable
```

Start Vim with

```
vim -u /path/to/vimrc
```

The plugin works well for me.

**Comment by phongvcao** [comment]
@itchyny okay I got the plugin work now. The problem is in my `BufWinEnter * :NERDTree...` command, it probably caused some conflicts with `vim-cursorword`.
