### ISSUE TITLE
機能の toggle を可能にしてほしい

### ISSUE THREAD

**Issue by lambdalisue** [itchyny/vim-cursorword#5]
便利に使わせていただいています。ただ、URL が大量に書かれたファイルにて URL の編集を行う際などハイライトされる部分がとても多い場合カーソルの動きが明らかに遅くなるため簡単にトグルができると助かります。

**Comment by itchyny** [comment]
```
let b:cursorword = 0
```

or

```
let g:cursorword = 0
```

してください。
個人的には https://github.com/itchyny/dotfiles/blob/ba1ef4e81dc3279c01e3fc6ff86e1b244468fd4d/.vimrc.yaml#L191-L194 みたいに設定しています。

**Comment by lambdalisue** [comment]
遅れましたが、挙動調整が出来ました。ありがとうございます ;-)

**Comment by itchyny** [comment]
了解です
