### ISSUE TITLE
idea: only underline the word under the curser if there is more than one of it in the document

### ISSUE THREAD

**Issue by kevgo** [itchyny/vim-cursorword#7]
Thanks for writing this great tool, I love it! Here is an idea: 

Underlining is supposed to highlight multiple occurrences of a word in the text. 
If there is only one occurrence of the word under the curser, it should not underline that word.
This helps see quickly that there are no other occurrences of that word in the text.

**Comment by itchyny** [comment]
Thanks for your feedback. The feature seems to be useful but it can degrade the performance. I put good performance in the first place in this plugin and searching the word though the document on (almost) every cursor motion will cost too much. I'm not sure it's still useful when the plugin only searches during the lines visible in the buffer window.

**Comment by kevgo** [comment]
If performance is a concern, maybe build up a [dictionary](http://learnvimscriptthehardway.stevelosh.com/chapters/37.html) of all words? It could look like this:

```viml
let words = {'word 1': 1, 'word 2', 3}   # "word 1" exists one time, "word 2" exists 3 times
```

Then, in order to decide whether to display the underline, just look up the number for the current word, and if it is > 1, display the underline.

**Comment by itchyny** [comment]
User can edit the buffer so we have to update the dictionary all the time.

**Comment by kevgo** [comment]
Hmm, good point. Creating the dictionary could be fast, though, since it just scans the words. Maybe add an option to let the user customize the behavior if there is a concern around performance for some people? 

If you completely disagree, feel free to close this issue.

**Comment by itchyny** [comment]
Thanks for you suggestion but no plan to implement this feature.
