### ISSUE TITLE
E28: No such highlight group name: CursorWord0 when vim-startify is lazy loaded by vim-plug

### ISSUE THREAD

**Issue by liuchengxu** [itchyny/vim-cursorword#8]
Hi, itchyny. I come across an odd problem when using vim-startify and vim-cursorword at the same time, which vim-startify is lazy loaded by vim-plug.

```vim
Plug 'mhinz/vim-startify', { 'on': 'Startify' }
Plug 'itchyny/vim-cursorword'
```
Then an annoying error occurs:
```
Error detected while processing function cursorword#matchadd:
line   13:
E28: No such highlight group name: CursorWord0
```

If vim-startify is loaded without lazy loading, all is fine.
```vim
Plug 'mhinz/vim-startify'
Plug 'itchyny/vim-cursorword'
```

Do you have any clue on this?

**Comment by itchyny** [comment]
I'm not sure what happens and I'll test your configuration tonight. Let me ask a few questions to reproduce the steps correctly; does it happens with only that two plugins (other plugins are commented out? and are you starting with `vim SOMEFILE` or just `vim`?

**Comment by liuchengxu** [comment]
Thanks!

There is no issue with the only two plugins loaded.

The error occurs when starting with`vim SOMEFILE`, not bare `vim`.

My vim configuration is [here](https://github.com/liuchengxu/space-vim). I have tried to reproduce it with a minimal ordinary vimrc, but I didn't make it :(.  Sorry for this.

Here is the minimal .spacevim in my configuration:

```vim
function! Layers()
    Layer 'better-defaults', {'exclude': 'mhinz/vim-startify'}
endfunction

function! UserInit()
    Plug 'mhinz/vim-startify', { 'on': 'Startify' }
    autocmd VimEnter * if !argc() | call plug#load('vim-startify') | endif
endfunction
```

**Comment by itchyny** [comment]
I tested the following vimrc
```vim
call plug#begin()
Plug 'mhinz/vim-startify', { 'on': 'Startify' }
Plug 'itchyny/vim-cursorword'
call plug#end()
```
and started with `vim -Nu path/to/vimrc path/to/vimrc` but I could not reproduce the error message.

**Comment by liuchengxu** [comment]
I also tested the vimrc you gave above. It's no problem. I guess there are some other plugins or congigurations involved in this issue, but I can't find it out at present. I'll try to make a minimal vimrc to reproduce it. But my configuration is a little complicated, so it may be not that easy. Thanks any way!

**Comment by pkhubpp8** [comment]
Hi， I met the similar problem when I use workspace plugin with cursorword plugin.
here is  vimrc
```
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'           "
Plugin 'thaerkh/vim-workspace'          " workspace
Plugin 'itchyny/vim-cursorword'
call vundle#end()            " required
filetype plugin indent on    " required
nnoremap <leader>s :ToggleWorkspace<CR>
let g:workspace_session_disable_on_args = 1
```
=============================================
step to reproduce:
1.plugin install vim-workspace
2."mkdir test && cd test" 
3."vim test.js" and add these blew into test.js
```
"use strict";
var fs = require('fs');
```
**note: must be no new \n in last line**
5.run ":ToggleWorkspace" or "<leader>s" to create work space
6."wq" write and quit
7.run "vim" in shell(not vim test.js), workspace plugin will auto open test.js, but these blew will show in terminal

"test.js" 2L, 38C
Error detected while processing function cursorword#matchadd:
line   14:
E28: No such highlight group name: CursorWord0

================================================
_:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 23 2016 13:33:55)
Included patches: 1-160
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +conceal         +farsi           +libcall         +mouse_netterm   +profile         +syntax          +visualextra
+arabic          +cryptv          +file_in_path    +linebreak       +mouse_sgr       +python/dyn      +tag_binary      +viminfo
+autocmd         +cscope          +find_in_path    +lispindent      -mouse_sysmouse  -python3         +tag_old_static  +vreplace
-balloon_eval    +cursorbind      +float           +listcmds        +mouse_urxvt     +quickfix        -tag_any_white   +wildignore
-browse          +cursorshape     +folding         +localmap        +mouse_xterm     +reltime         -tcl             +wildmenu
++builtin_terms  +dialog_con      -footer          -lua             +multi_byte      +rightleft       +terminfo        +windows
+byte_offset     +diff            +fork()          +menu            +multi_lang      +ruby/dyn        +termresponse    +writebackup
+cindent         +digraphs        +gettext         +mksession       -mzscheme        +scrollbind      +textobjects     -X11
-clientserver    -dnd             -hangul_input    +modify_fname    +netbeans_intg   +signs           +title           -xfontset
-clipboard       -ebcdic          +iconv           +mouse           +path_extra      +smartindent     -toolbar         -xim
+cmdline_compl   +emacs_tags      +insert_expand   -mouseshape      +perl            -sniff           +user_commands   -xsmp
+cmdline_hist    +eval            +jumplist        +mouse_dec       +persistent_undo +startuptime     +vertsplit       -xterm_clipboard
+cmdline_info    +ex_extra        +keymap          +mouse_gpm       +postscript      +statusline      +virtualedit     -xterm_save
+comments        +extra_search    +langmap         -mouse_jsbterm   +printer         -sun_workshop    +visual          -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L.  -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl  -
lselinux  -ltinfo -lacl -lattr -lgpm   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -
lm -lcrypt -lutil -lpthread -lc_

**Comment by rusdevops** [comment]
Please reopen this ticket. I also have the similar problem.

**Comment by itchyny** [comment]
This is an old ticket, so please file a new issue if you still have problem after updating the plugin.
