### ISSUE TITLE
Improperly highlighted when used with :set colorcolumn

### ISSUE THREAD

**Issue by nowox** [itchyny/vim-cursorword#9]
I've asked a question related to this Plugin here:

https://vi.stackexchange.com/questions/12158/improperly-highlighted-when-used-with-cursorcolumn

I am wondering if this can be an issue of `vim-cursorword`

NOTE: Perhaps this is related to this https://github.com/w0ng/vim-hybrid/issues/17

**Comment by itchyny** [comment]
The `vim-cursorword` only underlines the word and it works fine with colorsolumn. I think the problem is in vim-interestingwords, while I did not have time to investigate.

**Comment by nowox** [comment]
I have to investigate a bit though.

**Comment by itchyny** [comment]
Can you test with `let g:cursorword = 0`? This disables the plugin.

**Comment by nowox** [comment]
It's interesting, just avec your plugin I have the issue

![2017-04-20_21-36-26](https://cloud.githubusercontent.com/assets/1132849/25249236/7d2a10d2-2611-11e7-8d5a-c775c2ef01f2.png)

And after disabling the plugin it works: 

![2017-04-20_21-37-30](https://cloud.githubusercontent.com/assets/1132849/25249272/9ba35302-2611-11e7-9fa7-1b5817221146.png)

I am pretty sure the problem comes from `w0ng/vim-hybrid`, but I don't know what could be the issue.

**Comment by itchyny** [comment]
I tested with vim-hybrid but it works fine.
<img width="207" alt="screen shot 2017-04-21 at 10 18 25 am" src="https://cloud.githubusercontent.com/assets/375258/25258662/efa0efb8-267b-11e7-8577-16a6721dfd8a.png">

**Comment by nowox** [comment]
The issue doesn't appear on every keywords. On my previous example, only "white" keywords are affected by the issue.

**Comment by itchyny** [comment]
Still does not reproduce for me...
<img width="152" alt="screen shot 2017-04-21 at 4 59 16 pm" src="https://cloud.githubusercontent.com/assets/375258/25268495/df7459a8-26b3-11e7-859b-9ae3c5c1d390.png">

**Comment by nowox** [comment]
Perhaps you don't have vim8. I just tried on my Ubuntu:

![ubuntu](https://cloud.githubusercontent.com/assets/1132849/25304588/9dfd62d2-276a-11e7-80c5-e29096f21752.png)

Could you try with: 

- VIM - Vi IMproved 8.0 
- Same `.vimrc` as proposed
- Make sure `termguicolors` is enabled and your terminal support true colors.

**Comment by itchyny** [comment]
I have tested with the following .vimrc with 8.0.589 but still does not reproduce for me.
```vim
set nocompatible
filetype off
set runtimepath^=~/.vim/miv/cursorword
set termguicolors
set cursorcolumn
filetype plugin indent on
syntax enable
colorscheme hybird
```

**Comment by nowox** [comment]
I am afraid that if you use the wrong colorscheme you won't reproduce the issue. It is `hybrid` not `hybird`

**Comment by itchyny** [comment]
My bad, but still not reproducable for me. Please paste the result of `:hi Normal` and `:hi CursorColumn`.
